---
name: update-sources
on:
  workflow_dispatch:
  schedule:
    # runs every midnight
    - cron: "0 0 * * *"
  push:
    branches:
      - main
jobs:
  update-sources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run update script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./ci/update.sh
          bash ./ci/update.sh

      - name: Commit changes
        uses: EndBug/add-and-commit@v7.5.0
        with:
          default_author: github_actions
          message: "Update sources"
          add: '**/sources.json'
